### ISSUE TITLE
Relative path necessary for template file

### ISSUE THREAD

**Issue by rBurgett** [vitaliy-bobrov/angular-popper#2]
For usage in Electron applications, it is essential that the template file have a relative `./` path like the css file. The CSS file already has the correct path type. I'll file a PR. I can't imagine any reason that it would be necessary to do the template file path differently. Thanks!

**Comment by vitaliy-bobrov** [comment]
@rBurgett, thanks for PR, I'll plan to complete this lib and publish final version soon!

**Comment by vitaliy-bobrov** [comment]
@rBurgett, available in v1.0.0

**Comment by rBurgett** [comment]
@vitaliy-bobrov Thanks!
